-- Angol és Német szókincs A1-től B1-ig: 2 tantárgy, 6 szint, 24 csomag, kb. 500 szó.
-- Minden utasítás idempotens (OR IGNORE), újrafuttatható.
-- A csomagok Szókártyák (card_kind = word), kvíz nélkül, SM-2 gyakorláshoz.
-- Előlap az idegen szó, hátlap a magyar jelentés.

PRAGMA foreign_keys=OFF;

-- 1) Tantárgyak ---------------------------------------------------------------
INSERT OR IGNORE INTO subjects (id, title, icon, sort, created_at) VALUES
	('subj-angol', 'Angol', 'languages', 1, 0),
	('subj-nemet', 'Német', 'languages', 2, 0);
UPDATE subjects SET level_label = 'Szint' WHERE id IN ('subj-angol', 'subj-nemet');

-- 2) Szintek ------------------------------------------------------------------
INSERT OR IGNORE INTO levels (id, subject_id, title, sort) VALUES
	('level-angol-a1', 'subj-angol', 'A1', 0),
	('level-angol-a2', 'subj-angol', 'A2', 1),
	('level-angol-b1', 'subj-angol', 'B1', 2),
	('level-nemet-a1', 'subj-nemet', 'A1', 0),
	('level-nemet-a2', 'subj-nemet', 'A2', 1),
	('level-nemet-b1', 'subj-nemet', 'B1', 2);

-- 3) Tananyagok ---------------------------------------------------------------
INSERT OR IGNORE INTO materials (id, level_id, title, sort) VALUES
	('mat-angol-a1', 'level-angol-a1', 'Mindennapi alapok', 0),
	('mat-angol-a2', 'level-angol-a2', 'Mindennapi helyzetek', 0),
	('mat-angol-b1', 'level-angol-b1', 'Önálló témák', 0),
	('mat-nemet-a1', 'level-nemet-a1', 'Mindennapi alapok', 0),
	('mat-nemet-a2', 'level-nemet-a2', 'Mindennapi helyzetek', 0),
	('mat-nemet-b1', 'level-nemet-b1', 'Önálló témák', 0);

-- 4) Leckék -------------------------------------------------------------------
INSERT OR IGNORE INTO lessons (id, material_id, title, body_md, sort) VALUES
	('lesson-angol-a1-koszones', 'mat-angol-a1', 'Köszönések és bemutatkozás', 'Angol A1 szókincs: köszönések és bemutatkozás.', 0),
	('lesson-angol-a1-csalad', 'mat-angol-a1', 'Család és emberek', 'Angol A1 szókincs: családtagok és emberek.', 1),
	('lesson-angol-a1-etel', 'mat-angol-a1', 'Ételek és italok', 'Angol A1 szókincs: alapvető ételek és italok.', 2),
	('lesson-angol-a1-szamok', 'mat-angol-a1', 'Számok és időpontok', 'Angol A1 szókincs: számok és idővel kapcsolatos szavak.', 3),
	('lesson-angol-a2-otthon', 'mat-angol-a2', 'Otthon és lakás', 'Angol A2 szókincs: lakás, szobák és berendezés.', 0),
	('lesson-angol-a2-utazas', 'mat-angol-a2', 'Utazás és közlekedés', 'Angol A2 szókincs: utazás és útbaigazítás.', 1),
	('lesson-angol-a2-vasarlas', 'mat-angol-a2', 'Vásárlás és pénz', 'Angol A2 szókincs: bolt, árak és fizetés.', 2),
	('lesson-angol-a2-idojaras', 'mat-angol-a2', 'Időjárás és természet', 'Angol A2 szókincs: időjárás és évszakok.', 3),
	('lesson-angol-b1-munka', 'mat-angol-b1', 'Munka és iskola', 'Angol B1 szókincs: munkahely és tanulás.', 0),
	('lesson-angol-b1-egeszseg', 'mat-angol-b1', 'Egészség és test', 'Angol B1 szókincs: egészség, orvos és testrészek.', 1),
	('lesson-angol-b1-tech', 'mat-angol-b1', 'Technológia és média', 'Angol B1 szókincs: számítógép, internet és hírek.', 2),
	('lesson-angol-b1-velemeny', 'mat-angol-b1', 'Vélemény és érzések', 'Angol B1 szókincs: véleménykifejezés és érzelmek.', 3),
	('lesson-nemet-a1-begruesung', 'mat-nemet-a1', 'Köszönések és bemutatkozás', 'Német A1 szókincs: köszönések és bemutatkozás.', 0),
	('lesson-nemet-a1-familie', 'mat-nemet-a1', 'Család és emberek', 'Német A1 szókincs: családtagok és emberek.', 1),
	('lesson-nemet-a1-essen', 'mat-nemet-a1', 'Ételek és italok', 'Német A1 szókincs: alapvető ételek és italok.', 2),
	('lesson-nemet-a1-zahlen', 'mat-nemet-a1', 'Számok és időpontok', 'Német A1 szókincs: számok és idővel kapcsolatos szavak.', 3),
	('lesson-nemet-a2-wohnen', 'mat-nemet-a2', 'Otthon és lakás', 'Német A2 szókincs: lakás, szobák és berendezés.', 0),
	('lesson-nemet-a2-reisen', 'mat-nemet-a2', 'Utazás és közlekedés', 'Német A2 szókincs: utazás és útbaigazítás.', 1),
	('lesson-nemet-a2-einkaufen', 'mat-nemet-a2', 'Vásárlás és pénz', 'Német A2 szókincs: bolt, árak és fizetés.', 2),
	('lesson-nemet-a2-wetter', 'mat-nemet-a2', 'Időjárás és természet', 'Német A2 szókincs: időjárás és évszakok.', 3),
	('lesson-nemet-b1-arbeit', 'mat-nemet-b1', 'Munka és iskola', 'Német B1 szókincs: munkahely és tanulás.', 0),
	('lesson-nemet-b1-gesundheit', 'mat-nemet-b1', 'Egészség és test', 'Német B1 szókincs: egészség, orvos és testrészek.', 1),
	('lesson-nemet-b1-tech', 'mat-nemet-b1', 'Technológia és média', 'Német B1 szókincs: számítógép, internet és hírek.', 2),
	('lesson-nemet-b1-meinung', 'mat-nemet-b1', 'Vélemény és érzések', 'Német B1 szókincs: véleménykifejezés és érzelmek.', 3);

-- 5) Csomagok -----------------------------------------------------------------
INSERT OR IGNORE INTO lesson_card_packs (id, lesson_id, title, card_kind, sort) VALUES
	('lcp-angol-a1-koszones', 'lesson-angol-a1-koszones', 'Angol A1 - Köszönések', 'word', 0),
	('lcp-angol-a1-csalad', 'lesson-angol-a1-csalad', 'Angol A1 - Család', 'word', 0),
	('lcp-angol-a1-etel', 'lesson-angol-a1-etel', 'Angol A1 - Ételek', 'word', 0),
	('lcp-angol-a1-szamok', 'lesson-angol-a1-szamok', 'Angol A1 - Számok', 'word', 0),
	('lcp-angol-a2-otthon', 'lesson-angol-a2-otthon', 'Angol A2 - Otthon', 'word', 0),
	('lcp-angol-a2-utazas', 'lesson-angol-a2-utazas', 'Angol A2 - Utazás', 'word', 0),
	('lcp-angol-a2-vasarlas', 'lesson-angol-a2-vasarlas', 'Angol A2 - Vásárlás', 'word', 0),
	('lcp-angol-a2-idojaras', 'lesson-angol-a2-idojaras', 'Angol A2 - Időjárás', 'word', 0),
	('lcp-angol-b1-munka', 'lesson-angol-b1-munka', 'Angol B1 - Munka', 'word', 0),
	('lcp-angol-b1-egeszseg', 'lesson-angol-b1-egeszseg', 'Angol B1 - Egészség', 'word', 0),
	('lcp-angol-b1-tech', 'lesson-angol-b1-tech', 'Angol B1 - Technológia', 'word', 0),
	('lcp-angol-b1-velemeny', 'lesson-angol-b1-velemeny', 'Angol B1 - Vélemény', 'word', 0),
	('lcp-nemet-a1-begruesung', 'lesson-nemet-a1-begruesung', 'Német A1 - Köszönések', 'word', 0),
	('lcp-nemet-a1-familie', 'lesson-nemet-a1-familie', 'Német A1 - Család', 'word', 0),
	('lcp-nemet-a1-essen', 'lesson-nemet-a1-essen', 'Német A1 - Ételek', 'word', 0),
	('lcp-nemet-a1-zahlen', 'lesson-nemet-a1-zahlen', 'Német A1 - Számok', 'word', 0),
	('lcp-nemet-a2-wohnen', 'lesson-nemet-a2-wohnen', 'Német A2 - Otthon', 'word', 0),
	('lcp-nemet-a2-reisen', 'lesson-nemet-a2-reisen', 'Német A2 - Utazás', 'word', 0),
	('lcp-nemet-a2-einkaufen', 'lesson-nemet-a2-einkaufen', 'Német A2 - Vásárlás', 'word', 0),
	('lcp-nemet-a2-wetter', 'lesson-nemet-a2-wetter', 'Német A2 - Időjárás', 'word', 0),
	('lcp-nemet-b1-arbeit', 'lesson-nemet-b1-arbeit', 'Német B1 - Munka', 'word', 0),
	('lcp-nemet-b1-gesundheit', 'lesson-nemet-b1-gesundheit', 'Német B1 - Egészség', 'word', 0),
	('lcp-nemet-b1-tech', 'lesson-nemet-b1-tech', 'Német B1 - Technológia', 'word', 0),
	('lcp-nemet-b1-meinung', 'lesson-nemet-b1-meinung', 'Német B1 - Vélemény', 'word', 0);

-- 6) Angol A1 kártyák ----------------------------------------------------------
INSERT OR IGNORE INTO lesson_cards (id, lesson_id, section_slug, front, back, sort, pack_id) VALUES
	('lc-ena1k-01', 'lesson-angol-a1-koszones', 'szavak', 'hello', 'szia, hello', 0, 'lcp-angol-a1-koszones'),
	('lc-ena1k-02', 'lesson-angol-a1-koszones', 'szavak', 'good morning', 'jó reggelt', 1, 'lcp-angol-a1-koszones'),
	('lc-ena1k-03', 'lesson-angol-a1-koszones', 'szavak', 'good afternoon', 'jó napot', 2, 'lcp-angol-a1-koszones'),
	('lc-ena1k-04', 'lesson-angol-a1-koszones', 'szavak', 'good evening', 'jó estét', 3, 'lcp-angol-a1-koszones'),
	('lc-ena1k-05', 'lesson-angol-a1-koszones', 'szavak', 'good night', 'jó éjszakát', 4, 'lcp-angol-a1-koszones'),
	('lc-ena1k-06', 'lesson-angol-a1-koszones', 'szavak', 'goodbye', 'viszlát', 5, 'lcp-angol-a1-koszones'),
	('lc-ena1k-07', 'lesson-angol-a1-koszones', 'szavak', 'bye', 'szia búcsúzáskor', 6, 'lcp-angol-a1-koszones'),
	('lc-ena1k-08', 'lesson-angol-a1-koszones', 'szavak', 'please', 'kérem, legyen szíves', 7, 'lcp-angol-a1-koszones'),
	('lc-ena1k-09', 'lesson-angol-a1-koszones', 'szavak', 'thank you', 'köszönöm', 8, 'lcp-angol-a1-koszones'),
	('lc-ena1k-10', 'lesson-angol-a1-koszones', 'szavak', 'thanks', 'köszi', 9, 'lcp-angol-a1-koszones'),
	('lc-ena1k-11', 'lesson-angol-a1-koszones', 'szavak', 'sorry', 'bocsánat', 10, 'lcp-angol-a1-koszones'),
	('lc-ena1k-12', 'lesson-angol-a1-koszones', 'szavak', 'excuse me', 'elnézést', 11, 'lcp-angol-a1-koszones'),
	('lc-ena1k-13', 'lesson-angol-a1-koszones', 'szavak', 'yes', 'igen', 12, 'lcp-angol-a1-koszones'),
	('lc-ena1k-14', 'lesson-angol-a1-koszones', 'szavak', 'no', 'nem', 13, 'lcp-angol-a1-koszones'),
	('lc-ena1k-15', 'lesson-angol-a1-koszones', 'szavak', 'my name is', 'a nevem', 14, 'lcp-angol-a1-koszones'),
	('lc-ena1k-16', 'lesson-angol-a1-koszones', 'szavak', 'what is your name', 'hogy hívnak', 15, 'lcp-angol-a1-koszones'),
	('lc-ena1k-17', 'lesson-angol-a1-koszones', 'szavak', 'nice to meet you', 'örülök hogy megismertelek', 16, 'lcp-angol-a1-koszones'),
	('lc-ena1k-18', 'lesson-angol-a1-koszones', 'szavak', 'how are you', 'hogy vagy', 17, 'lcp-angol-a1-koszones'),
	('lc-ena1k-19', 'lesson-angol-a1-koszones', 'szavak', 'I am fine', 'jól vagyok', 18, 'lcp-angol-a1-koszones'),
	('lc-ena1k-20', 'lesson-angol-a1-koszones', 'szavak', 'see you', 'viszlát, majd találkozunk', 19, 'lcp-angol-a1-koszones');

INSERT OR IGNORE INTO lesson_cards (id, lesson_id, section_slug, front, back, sort, pack_id) VALUES
	('lc-ena1c-01', 'lesson-angol-a1-csalad', 'szavak', 'mother', 'anya', 0, 'lcp-angol-a1-csalad'),
	('lc-ena1c-02', 'lesson-angol-a1-csalad', 'szavak', 'father', 'apa', 1, 'lcp-angol-a1-csalad'),
	('lc-ena1c-03', 'lesson-angol-a1-csalad', 'szavak', 'parents', 'szülők', 2, 'lcp-angol-a1-csalad'),
	('lc-ena1c-04', 'lesson-angol-a1-csalad', 'szavak', 'brother', 'fiútestvér', 3, 'lcp-angol-a1-csalad'),
	('lc-ena1c-05', 'lesson-angol-a1-csalad', 'szavak', 'sister', 'lánytestvér', 4, 'lcp-angol-a1-csalad'),
	('lc-ena1c-06', 'lesson-angol-a1-csalad', 'szavak', 'son', 'fiú gyermek', 5, 'lcp-angol-a1-csalad'),
	('lc-ena1c-07', 'lesson-angol-a1-csalad', 'szavak', 'daughter', 'lány gyermek', 6, 'lcp-angol-a1-csalad'),
	('lc-ena1c-08', 'lesson-angol-a1-csalad', 'szavak', 'child', 'gyerek', 7, 'lcp-angol-a1-csalad'),
	('lc-ena1c-09', 'lesson-angol-a1-csalad', 'szavak', 'baby', 'baba', 8, 'lcp-angol-a1-csalad'),
	('lc-ena1c-10', 'lesson-angol-a1-csalad', 'szavak', 'husband', 'férj', 9, 'lcp-angol-a1-csalad'),
	('lc-ena1c-11', 'lesson-angol-a1-csalad', 'szavak', 'wife', 'feleség', 10, 'lcp-angol-a1-csalad'),
	('lc-ena1c-12', 'lesson-angol-a1-csalad', 'szavak', 'family', 'család', 11, 'lcp-angol-a1-csalad'),
	('lc-ena1c-13', 'lesson-angol-a1-csalad', 'szavak', 'grandmother', 'nagymama', 12, 'lcp-angol-a1-csalad'),
	('lc-ena1c-14', 'lesson-angol-a1-csalad', 'szavak', 'grandfather', 'nagypapa', 13, 'lcp-angol-a1-csalad'),
	('lc-ena1c-15', 'lesson-angol-a1-csalad', 'szavak', 'uncle', 'nagybácsi', 14, 'lcp-angol-a1-csalad'),
	('lc-ena1c-16', 'lesson-angol-a1-csalad', 'szavak', 'aunt', 'nagynéni', 15, 'lcp-angol-a1-csalad'),
	('lc-ena1c-17', 'lesson-angol-a1-csalad', 'szavak', 'cousin', 'unokatestvér', 16, 'lcp-angol-a1-csalad'),
	('lc-ena1c-18', 'lesson-angol-a1-csalad', 'szavak', 'friend', 'barát', 17, 'lcp-angol-a1-csalad'),
	('lc-ena1c-19', 'lesson-angol-a1-csalad', 'szavak', 'boy', 'fiú', 18, 'lcp-angol-a1-csalad'),
	('lc-ena1c-20', 'lesson-angol-a1-csalad', 'szavak', 'girl', 'lány', 19, 'lcp-angol-a1-csalad'),
	('lc-ena1c-21', 'lesson-angol-a1-csalad', 'szavak', 'man', 'férfi', 20, 'lcp-angol-a1-csalad'),
	('lc-ena1c-22', 'lesson-angol-a1-csalad', 'szavak', 'woman', 'nő', 21, 'lcp-angol-a1-csalad');

INSERT OR IGNORE INTO lesson_cards (id, lesson_id, section_slug, front, back, sort, pack_id) VALUES
	('lc-ena1e-01', 'lesson-angol-a1-etel', 'szavak', 'apple', 'alma', 0, 'lcp-angol-a1-etel'),
	('lc-ena1e-02', 'lesson-angol-a1-etel', 'szavak', 'banana', 'banán', 1, 'lcp-angol-a1-etel'),
	('lc-ena1e-03', 'lesson-angol-a1-etel', 'szavak', 'orange', 'narancs', 2, 'lcp-angol-a1-etel'),
	('lc-ena1e-04', 'lesson-angol-a1-etel', 'szavak', 'bread', 'kenyér', 3, 'lcp-angol-a1-etel'),
	('lc-ena1e-05', 'lesson-angol-a1-etel', 'szavak', 'butter', 'vaj', 4, 'lcp-angol-a1-etel'),
	('lc-ena1e-06', 'lesson-angol-a1-etel', 'szavak', 'cheese', 'sajt', 5, 'lcp-angol-a1-etel'),
	('lc-ena1e-07', 'lesson-angol-a1-etel', 'szavak', 'egg', 'tojás', 6, 'lcp-angol-a1-etel'),
	('lc-ena1e-08', 'lesson-angol-a1-etel', 'szavak', 'milk', 'tej', 7, 'lcp-angol-a1-etel'),
	('lc-ena1e-09', 'lesson-angol-a1-etel', 'szavak', 'coffee', 'kávé', 8, 'lcp-angol-a1-etel'),
	('lc-ena1e-10', 'lesson-angol-a1-etel', 'szavak', 'tea', 'tea', 9, 'lcp-angol-a1-etel'),
	('lc-ena1e-11', 'lesson-angol-a1-etel', 'szavak', 'water', 'víz', 10, 'lcp-angol-a1-etel'),
	('lc-ena1e-12', 'lesson-angol-a1-etel', 'szavak', 'juice', 'gyümölcslé', 11, 'lcp-angol-a1-etel'),
	('lc-ena1e-13', 'lesson-angol-a1-etel', 'szavak', 'meat', 'hús', 12, 'lcp-angol-a1-etel'),
	('lc-ena1e-14', 'lesson-angol-a1-etel', 'szavak', 'fish', 'hal', 13, 'lcp-angol-a1-etel'),
	('lc-ena1e-15', 'lesson-angol-a1-etel', 'szavak', 'chicken', 'csirke', 14, 'lcp-angol-a1-etel'),
	('lc-ena1e-16', 'lesson-angol-a1-etel', 'szavak', 'rice', 'rizs', 15, 'lcp-angol-a1-etel'),
	('lc-ena1e-17', 'lesson-angol-a1-etel', 'szavak', 'pasta', 'tészta', 16, 'lcp-angol-a1-etel'),
	('lc-ena1e-18', 'lesson-angol-a1-etel', 'szavak', 'soup', 'leves', 17, 'lcp-angol-a1-etel'),
	('lc-ena1e-19', 'lesson-angol-a1-etel', 'szavak', 'salad', 'saláta', 18, 'lcp-angol-a1-etel'),
	('lc-ena1e-20', 'lesson-angol-a1-etel', 'szavak', 'cake', 'torta, sütemény', 19, 'lcp-angol-a1-etel'),
	('lc-ena1e-21', 'lesson-angol-a1-etel', 'szavak', 'sugar', 'cukor', 20, 'lcp-angol-a1-etel'),
	('lc-ena1e-22', 'lesson-angol-a1-etel', 'szavak', 'salt', 'só', 21, 'lcp-angol-a1-etel');

INSERT OR IGNORE INTO lesson_cards (id, lesson_id, section_slug, front, back, sort, pack_id) VALUES
	('lc-ena1s-01', 'lesson-angol-a1-szamok', 'szavak', 'zero', 'nulla', 0, 'lcp-angol-a1-szamok'),
	('lc-ena1s-02', 'lesson-angol-a1-szamok', 'szavak', 'one', 'egy', 1, 'lcp-angol-a1-szamok'),
	('lc-ena1s-03', 'lesson-angol-a1-szamok', 'szavak', 'two', 'kettő', 2, 'lcp-angol-a1-szamok'),
	('lc-ena1s-04', 'lesson-angol-a1-szamok', 'szavak', 'three', 'három', 3, 'lcp-angol-a1-szamok'),
	('lc-ena1s-05', 'lesson-angol-a1-szamok', 'szavak', 'four', 'négy', 4, 'lcp-angol-a1-szamok'),
	('lc-ena1s-06', 'lesson-angol-a1-szamok', 'szavak', 'five', 'öt', 5, 'lcp-angol-a1-szamok'),
	('lc-ena1s-07', 'lesson-angol-a1-szamok', 'szavak', 'six', 'hat', 6, 'lcp-angol-a1-szamok'),
	('lc-ena1s-08', 'lesson-angol-a1-szamok', 'szavak', 'seven', 'hét', 7, 'lcp-angol-a1-szamok'),
	('lc-ena1s-09', 'lesson-angol-a1-szamok', 'szavak', 'eight', 'nyolc', 8, 'lcp-angol-a1-szamok'),
	('lc-ena1s-10', 'lesson-angol-a1-szamok', 'szavak', 'nine', 'kilenc', 9, 'lcp-angol-a1-szamok'),
	('lc-ena1s-11', 'lesson-angol-a1-szamok', 'szavak', 'ten', 'tíz', 10, 'lcp-angol-a1-szamok'),
	('lc-ena1s-12', 'lesson-angol-a1-szamok', 'szavak', 'eleven', 'tizenegy', 11, 'lcp-angol-a1-szamok'),
	('lc-ena1s-13', 'lesson-angol-a1-szamok', 'szavak', 'twelve', 'tizenkettő', 12, 'lcp-angol-a1-szamok'),
	('lc-ena1s-14', 'lesson-angol-a1-szamok', 'szavak', 'twenty', 'húsz', 13, 'lcp-angol-a1-szamok'),
	('lc-ena1s-15', 'lesson-angol-a1-szamok', 'szavak', 'hundred', 'száz', 14, 'lcp-angol-a1-szamok'),
	('lc-ena1s-16', 'lesson-angol-a1-szamok', 'szavak', 'thousand', 'ezer', 15, 'lcp-angol-a1-szamok'),
	('lc-ena1s-17', 'lesson-angol-a1-szamok', 'szavak', 'today', 'ma', 16, 'lcp-angol-a1-szamok'),
	('lc-ena1s-18', 'lesson-angol-a1-szamok', 'szavak', 'tomorrow', 'holnap', 17, 'lcp-angol-a1-szamok'),
	('lc-ena1s-19', 'lesson-angol-a1-szamok', 'szavak', 'yesterday', 'tegnap', 18, 'lcp-angol-a1-szamok'),
	('lc-ena1s-20', 'lesson-angol-a1-szamok', 'szavak', 'day', 'nap', 19, 'lcp-angol-a1-szamok'),
	('lc-ena1s-21', 'lesson-angol-a1-szamok', 'szavak', 'week', 'hét időszak', 20, 'lcp-angol-a1-szamok'),
	('lc-ena1s-22', 'lesson-angol-a1-szamok', 'szavak', 'month', 'hónap', 21, 'lcp-angol-a1-szamok');

-- 7) Angol A2 kártyák ----------------------------------------------------------
INSERT OR IGNORE INTO lesson_cards (id, lesson_id, section_slug, front, back, sort, pack_id) VALUES
	('lc-ena2o-01', 'lesson-angol-a2-otthon', 'szavak', 'house', 'ház', 0, 'lcp-angol-a2-otthon'),
	('lc-ena2o-02', 'lesson-angol-a2-otthon', 'szavak', 'flat', 'lakás', 1, 'lcp-angol-a2-otthon'),
	('lc-ena2o-03', 'lesson-angol-a2-otthon', 'szavak', 'room', 'szoba', 2, 'lcp-angol-a2-otthon'),
	('lc-ena2o-04', 'lesson-angol-a2-otthon', 'szavak', 'kitchen', 'konyha', 3, 'lcp-angol-a2-otthon'),
	('lc-ena2o-05', 'lesson-angol-a2-otthon', 'szavak', 'bedroom', 'hálószoba', 4, 'lcp-angol-a2-otthon'),
	('lc-ena2o-06', 'lesson-angol-a2-otthon', 'szavak', 'bathroom', 'fürdőszoba', 5, 'lcp-angol-a2-otthon'),
	('lc-ena2o-07', 'lesson-angol-a2-otthon', 'szavak', 'living room', 'nappali', 6, 'lcp-angol-a2-otthon'),
	('lc-ena2o-08', 'lesson-angol-a2-otthon', 'szavak', 'door', 'ajtó', 7, 'lcp-angol-a2-otthon'),
	('lc-ena2o-09', 'lesson-angol-a2-otthon', 'szavak', 'window', 'ablak', 8, 'lcp-angol-a2-otthon'),
	('lc-ena2o-10', 'lesson-angol-a2-otthon', 'szavak', 'table', 'asztal', 9, 'lcp-angol-a2-otthon'),
	('lc-ena2o-11', 'lesson-angol-a2-otthon', 'szavak', 'chair', 'szék', 10, 'lcp-angol-a2-otthon'),
	('lc-ena2o-12', 'lesson-angol-a2-otthon', 'szavak', 'bed', 'ágy', 11, 'lcp-angol-a2-otthon'),
	('lc-ena2o-13', 'lesson-angol-a2-otthon', 'szavak', 'lamp', 'lámpa', 12, 'lcp-angol-a2-otthon'),
	('lc-ena2o-14', 'lesson-angol-a2-otthon', 'szavak', 'garden', 'kert', 13, 'lcp-angol-a2-otthon'),
	('lc-ena2o-15', 'lesson-angol-a2-otthon', 'szavak', 'wall', 'fal', 14, 'lcp-angol-a2-otthon'),
	('lc-ena2o-16', 'lesson-angol-a2-otthon', 'szavak', 'floor', 'padló', 15, 'lcp-angol-a2-otthon'),
	('lc-ena2o-17', 'lesson-angol-a2-otthon', 'szavak', 'key', 'kulcs', 16, 'lcp-angol-a2-otthon'),
	('lc-ena2o-18', 'lesson-angol-a2-otthon', 'szavak', 'rent', 'bérelni, bérleti díj', 17, 'lcp-angol-a2-otthon'),
	('lc-ena2o-19', 'lesson-angol-a2-otthon', 'szavak', 'neighbour', 'szomszéd', 18, 'lcp-angol-a2-otthon'),
	('lc-ena2o-20', 'lesson-angol-a2-otthon', 'szavak', 'address', 'cím', 19, 'lcp-angol-a2-otthon');

INSERT OR IGNORE INTO lesson_cards (id, lesson_id, section_slug, front, back, sort, pack_id) VALUES
	('lc-ena2u-01', 'lesson-angol-a2-utazas', 'szavak', 'travel', 'utazni, utazás', 0, 'lcp-angol-a2-utazas'),
	('lc-ena2u-02', 'lesson-angol-a2-utazas', 'szavak', 'trip', 'kirándulás, út', 1, 'lcp-angol-a2-utazas'),
	('lc-ena2u-03', 'lesson-angol-a2-utazas', 'szavak', 'ticket', 'jegy', 2, 'lcp-angol-a2-utazas'),
	('lc-ena2u-04', 'lesson-angol-a2-utazas', 'szavak', 'train', 'vonat', 3, 'lcp-angol-a2-utazas'),
	('lc-ena2u-05', 'lesson-angol-a2-utazas', 'szavak', 'bus', 'busz', 4, 'lcp-angol-a2-utazas'),
	('lc-ena2u-06', 'lesson-angol-a2-utazas', 'szavak', 'car', 'autó', 5, 'lcp-angol-a2-utazas'),
	('lc-ena2u-07', 'lesson-angol-a2-utazas', 'szavak', 'plane', 'repülőgép', 6, 'lcp-angol-a2-utazas'),
	('lc-ena2u-08', 'lesson-angol-a2-utazas', 'szavak', 'airport', 'repülőtér', 7, 'lcp-angol-a2-utazas'),
	('lc-ena2u-09', 'lesson-angol-a2-utazas', 'szavak', 'station', 'állomás', 8, 'lcp-angol-a2-utazas'),
	('lc-ena2u-10', 'lesson-angol-a2-utazas', 'szavak', 'map', 'térkép', 9, 'lcp-angol-a2-utazas'),
	('lc-ena2u-11', 'lesson-angol-a2-utazas', 'szavak', 'left', 'balra, bal', 10, 'lcp-angol-a2-utazas'),
	('lc-ena2u-12', 'lesson-angol-a2-utazas', 'szavak', 'right', 'jobbra, jobb', 11, 'lcp-angol-a2-utazas'),
	('lc-ena2u-13', 'lesson-angol-a2-utazas', 'szavak', 'straight', 'egyenesen', 12, 'lcp-angol-a2-utazas'),
	('lc-ena2u-14', 'lesson-angol-a2-utazas', 'szavak', 'street', 'utca', 13, 'lcp-angol-a2-utazas'),
	('lc-ena2u-15', 'lesson-angol-a2-utazas', 'szavak', 'city', 'város', 14, 'lcp-angol-a2-utazas'),
	('lc-ena2u-16', 'lesson-angol-a2-utazas', 'szavak', 'village', 'falu', 15, 'lcp-angol-a2-utazas'),
	('lc-ena2u-17', 'lesson-angol-a2-utazas', 'szavak', 'hotel', 'szálloda', 16, 'lcp-angol-a2-utazas'),
	('lc-ena2u-18', 'lesson-angol-a2-utazas', 'szavak', 'passport', 'útlevél', 17, 'lcp-angol-a2-utazas'),
	('lc-ena2u-19', 'lesson-angol-a2-utazas', 'szavak', 'suitcase', 'bőrönd', 18, 'lcp-angol-a2-utazas'),
	('lc-ena2u-20', 'lesson-angol-a2-utazas', 'szavak', 'photo', 'fénykép', 19, 'lcp-angol-a2-utazas'),
	('lc-ena2u-21', 'lesson-angol-a2-utazas', 'szavak', 'holiday', 'nyaralás, ünnep', 20, 'lcp-angol-a2-utazas'),
	('lc-ena2u-22', 'lesson-angol-a2-utazas', 'szavak', 'luggage', 'csomag, poggyász', 21, 'lcp-angol-a2-utazas');

INSERT OR IGNORE INTO lesson_cards (id, lesson_id, section_slug, front, back, sort, pack_id) VALUES
	('lc-ena2v-01', 'lesson-angol-a2-vasarlas', 'szavak', 'shop', 'bolt, vásárolni', 0, 'lcp-angol-a2-vasarlas'),
	('lc-ena2v-02', 'lesson-angol-a2-vasarlas', 'szavak', 'market', 'piac', 1, 'lcp-angol-a2-vasarlas'),
	('lc-ena2v-03', 'lesson-angol-a2-vasarlas', 'szavak', 'price', 'ár', 2, 'lcp-angol-a2-vasarlas'),
	('lc-ena2v-04', 'lesson-angol-a2-vasarlas', 'szavak', 'cheap', 'olcsó', 3, 'lcp-angol-a2-vasarlas'),
	('lc-ena2v-05', 'lesson-angol-a2-vasarlas', 'szavak', 'expensive', 'drága', 4, 'lcp-angol-a2-vasarlas'),
	('lc-ena2v-06', 'lesson-angol-a2-vasarlas', 'szavak', 'money', 'pénz', 5, 'lcp-angol-a2-vasarlas'),
	('lc-ena2v-07', 'lesson-angol-a2-vasarlas', 'szavak', 'coin', 'érme', 6, 'lcp-angol-a2-vasarlas'),
	('lc-ena2v-08', 'lesson-angol-a2-vasarlas', 'szavak', 'card', 'kártya', 7, 'lcp-angol-a2-vasarlas'),
	('lc-ena2v-09', 'lesson-angol-a2-vasarlas', 'szavak', 'cash', 'készpénz', 8, 'lcp-angol-a2-vasarlas'),
	('lc-ena2v-10', 'lesson-angol-a2-vasarlas', 'szavak', 'change', 'visszajáró pénz', 9, 'lcp-angol-a2-vasarlas'),
	('lc-ena2v-11', 'lesson-angol-a2-vasarlas', 'szavak', 'receipt', 'nyugta, blokk', 10, 'lcp-angol-a2-vasarlas'),
	('lc-ena2v-12', 'lesson-angol-a2-vasarlas', 'szavak', 'bag', 'táska, zacskó', 11, 'lcp-angol-a2-vasarlas'),
	('lc-ena2v-13', 'lesson-angol-a2-vasarlas', 'szavak', 'size', 'méret', 12, 'lcp-angol-a2-vasarlas'),
	('lc-ena2v-14', 'lesson-angol-a2-vasarlas', 'szavak', 'small', 'kicsi', 13, 'lcp-angol-a2-vasarlas'),
	('lc-ena2v-15', 'lesson-angol-a2-vasarlas', 'szavak', 'big', 'nagy', 14, 'lcp-angol-a2-vasarlas'),
	('lc-ena2v-16', 'lesson-angol-a2-vasarlas', 'szavak', 'sale', 'akció, leárazás', 15, 'lcp-angol-a2-vasarlas'),
	('lc-ena2v-17', 'lesson-angol-a2-vasarlas', 'szavak', 'open', 'nyitva, kinyitni', 16, 'lcp-angol-a2-vasarlas'),
	('lc-ena2v-18', 'lesson-angol-a2-vasarlas', 'szavak', 'closed', 'zárva', 17, 'lcp-angol-a2-vasarlas'),
	('lc-ena2v-19', 'lesson-angol-a2-vasarlas', 'szavak', 'buy', 'megvenni', 18, 'lcp-angol-a2-vasarlas'),
	('lc-ena2v-20', 'lesson-angol-a2-vasarlas', 'szavak', 'pay', 'fizetni', 19, 'lcp-angol-a2-vasarlas');

INSERT OR IGNORE INTO lesson_cards (id, lesson_id, section_slug, front, back, sort, pack_id) VALUES
	('lc-ena2i-01', 'lesson-angol-a2-idojaras', 'szavak', 'weather', 'időjárás', 0, 'lcp-angol-a2-idojaras'),
	('lc-ena2i-02', 'lesson-angol-a2-idojaras', 'szavak', 'sun', 'nap égitest', 1, 'lcp-angol-a2-idojaras'),
	('lc-ena2i-03', 'lesson-angol-a2-idojaras', 'szavak', 'rain', 'eső', 2, 'lcp-angol-a2-idojaras'),
	('lc-ena2i-04', 'lesson-angol-a2-idojaras', 'szavak', 'snow', 'hó', 3, 'lcp-angol-a2-idojaras'),
	('lc-ena2i-05', 'lesson-angol-a2-idojaras', 'szavak', 'wind', 'szél', 4, 'lcp-angol-a2-idojaras'),
	('lc-ena2i-06', 'lesson-angol-a2-idojaras', 'szavak', 'cloud', 'felhő', 5, 'lcp-angol-a2-idojaras'),
	('lc-ena2i-07', 'lesson-angol-a2-idojaras', 'szavak', 'sky', 'égbolt', 6, 'lcp-angol-a2-idojaras'),
	('lc-ena2i-08', 'lesson-angol-a2-idojaras', 'szavak', 'hot', 'forró, meleg', 7, 'lcp-angol-a2-idojaras'),
	('lc-ena2i-09', 'lesson-angol-a2-idojaras', 'szavak', 'cold', 'hideg', 8, 'lcp-angol-a2-idojaras'),
	('lc-ena2i-10', 'lesson-angol-a2-idojaras', 'szavak', 'warm', 'meleg, enyhe', 9, 'lcp-angol-a2-idojaras'),
	('lc-ena2i-11', 'lesson-angol-a2-idojaras', 'szavak', 'cool', 'hűvös', 10, 'lcp-angol-a2-idojaras'),
	('lc-ena2i-12', 'lesson-angol-a2-idojaras', 'szavak', 'storm', 'vihar', 11, 'lcp-angol-a2-idojaras'),
	('lc-ena2i-13', 'lesson-angol-a2-idojaras', 'szavak', 'fog', 'köd', 12, 'lcp-angol-a2-idojaras'),
	('lc-ena2i-14', 'lesson-angol-a2-idojaras', 'szavak', 'ice', 'jég', 13, 'lcp-angol-a2-idojaras'),
	('lc-ena2i-15', 'lesson-angol-a2-idojaras', 'szavak', 'season', 'évszak', 14, 'lcp-angol-a2-idojaras'),
	('lc-ena2i-16', 'lesson-angol-a2-idojaras', 'szavak', 'spring', 'tavasz', 15, 'lcp-angol-a2-idojaras'),
	('lc-ena2i-17', 'lesson-angol-a2-idojaras', 'szavak', 'summer', 'nyár', 16, 'lcp-angol-a2-idojaras'),
	('lc-ena2i-18', 'lesson-angol-a2-idojaras', 'szavak', 'autumn', 'ősz', 17, 'lcp-angol-a2-idojaras'),
	('lc-ena2i-19', 'lesson-angol-a2-idojaras', 'szavak', 'winter', 'tél', 18, 'lcp-angol-a2-idojaras'),
	('lc-ena2i-20', 'lesson-angol-a2-idojaras', 'szavak', 'temperature', 'hőmérséklet', 19, 'lcp-angol-a2-idojaras');

-- 8) Angol B1 kártyák ----------------------------------------------------------
INSERT OR IGNORE INTO lesson_cards (id, lesson_id, section_slug, front, back, sort, pack_id) VALUES
	('lc-enb1m-01', 'lesson-angol-b1-munka', 'szavak', 'job', 'munka, állás', 0, 'lcp-angol-b1-munka'),
	('lc-enb1m-02', 'lesson-angol-b1-munka', 'szavak', 'work', 'dolgozni, munka', 1, 'lcp-angol-b1-munka'),
	('lc-enb1m-03', 'lesson-angol-b1-munka', 'szavak', 'office', 'iroda', 2, 'lcp-angol-b1-munka'),
	('lc-enb1m-04', 'lesson-angol-b1-munka', 'szavak', 'colleague', 'kolléga', 3, 'lcp-angol-b1-munka'),
	('lc-enb1m-05', 'lesson-angol-b1-munka', 'szavak', 'boss', 'főnök', 4, 'lcp-angol-b1-munka'),
	('lc-enb1m-06', 'lesson-angol-b1-munka', 'szavak', 'meeting', 'értekezlet', 5, 'lcp-angol-b1-munka'),
	('lc-enb1m-07', 'lesson-angol-b1-munka', 'szavak', 'email', 'e-mail', 6, 'lcp-angol-b1-munka'),
	('lc-enb1m-08', 'lesson-angol-b1-munka', 'szavak', 'phone call', 'telefonhívás', 7, 'lcp-angol-b1-munka'),
	('lc-enb1m-09', 'lesson-angol-b1-munka', 'szavak', 'salary', 'fizetés', 8, 'lcp-angol-b1-munka'),
	('lc-enb1m-10', 'lesson-angol-b1-munka', 'szavak', 'application', 'jelentkezés, pályázat', 9, 'lcp-angol-b1-munka'),
	('lc-enb1m-11', 'lesson-angol-b1-munka', 'szavak', 'interview', 'interjú', 10, 'lcp-angol-b1-munka'),
	('lc-enb1m-12', 'lesson-angol-b1-munka', 'szavak', 'school', 'iskola', 11, 'lcp-angol-b1-munka'),
	('lc-enb1m-13', 'lesson-angol-b1-munka', 'szavak', 'teacher', 'tanár', 12, 'lcp-angol-b1-munka'),
	('lc-enb1m-14', 'lesson-angol-b1-munka', 'szavak', 'student', 'diák, hallgató', 13, 'lcp-angol-b1-munka'),
	('lc-enb1m-15', 'lesson-angol-b1-munka', 'szavak', 'lesson', 'lecke, óra', 14, 'lcp-angol-b1-munka'),
	('lc-enb1m-16', 'lesson-angol-b1-munka', 'szavak', 'homework', 'házi feladat', 15, 'lcp-angol-b1-munka'),
	('lc-enb1m-17', 'lesson-angol-b1-munka', 'szavak', 'exam', 'vizsga', 16, 'lcp-angol-b1-munka'),
	('lc-enb1m-18', 'lesson-angol-b1-munka', 'szavak', 'university', 'egyetem', 17, 'lcp-angol-b1-munka'),
	('lc-enb1m-19', 'lesson-angol-b1-munka', 'szavak', 'knowledge', 'tudás', 18, 'lcp-angol-b1-munka'),
	('lc-enb1m-20', 'lesson-angol-b1-munka', 'szavak', 'skill', 'készség', 19, 'lcp-angol-b1-munka'),
	('lc-enb1m-21', 'lesson-angol-b1-munka', 'szavak', 'experience', 'tapasztalat', 20, 'lcp-angol-b1-munka'),
	('lc-enb1m-22', 'lesson-angol-b1-munka', 'szavak', 'success', 'siker', 21, 'lcp-angol-b1-munka');

INSERT OR IGNORE INTO lesson_cards (id, lesson_id, section_slug, front, back, sort, pack_id) VALUES
	('lc-enb1e-01', 'lesson-angol-b1-egeszseg', 'szavak', 'health', 'egészség', 0, 'lcp-angol-b1-egeszseg'),
	('lc-enb1e-02', 'lesson-angol-b1-egeszseg', 'szavak', 'doctor', 'orvos', 1, 'lcp-angol-b1-egeszseg'),
	('lc-enb1e-03', 'lesson-angol-b1-egeszseg', 'szavak', 'hospital', 'kórház', 2, 'lcp-angol-b1-egeszseg'),
	('lc-enb1e-04', 'lesson-angol-b1-egeszseg', 'szavak', 'medicine', 'gyógyszer', 3, 'lcp-angol-b1-egeszseg'),
	('lc-enb1e-05', 'lesson-angol-b1-egeszseg', 'szavak', 'pain', 'fájdalom', 4, 'lcp-angol-b1-egeszseg'),
	('lc-enb1e-06', 'lesson-angol-b1-egeszseg', 'szavak', 'headache', 'fejfájás', 5, 'lcp-angol-b1-egeszseg'),
	('lc-enb1e-07', 'lesson-angol-b1-egeszseg', 'szavak', 'fever', 'láz', 6, 'lcp-angol-b1-egeszseg'),
	('lc-enb1e-08', 'lesson-angol-b1-egeszseg', 'szavak', 'cough', 'köhögés', 7, 'lcp-angol-b1-egeszseg'),
	('lc-enb1e-09', 'lesson-angol-b1-egeszseg', 'szavak', 'tired', 'fáradt', 8, 'lcp-angol-b1-egeszseg'),
	('lc-enb1e-10', 'lesson-angol-b1-egeszseg', 'szavak', 'rest', 'pihenés', 9, 'lcp-angol-b1-egeszseg'),
	('lc-enb1e-11', 'lesson-angol-b1-egeszseg', 'szavak', 'sleep', 'alvás', 10, 'lcp-angol-b1-egeszseg'),
	('lc-enb1e-12', 'lesson-angol-b1-egeszseg', 'szavak', 'healthy', 'egészséges', 11, 'lcp-angol-b1-egeszseg'),
	('lc-enb1e-13', 'lesson-angol-b1-egeszseg', 'szavak', 'sick', 'beteg', 12, 'lcp-angol-b1-egeszseg'),
	('lc-enb1e-14', 'lesson-angol-b1-egeszseg', 'szavak', 'body', 'test', 13, 'lcp-angol-b1-egeszseg'),
	('lc-enb1e-15', 'lesson-angol-b1-egeszseg', 'szavak', 'heart', 'szív', 14, 'lcp-angol-b1-egeszseg'),
	('lc-enb1e-16', 'lesson-angol-b1-egeszseg', 'szavak', 'blood', 'vér', 15, 'lcp-angol-b1-egeszseg'),
	('lc-enb1e-17', 'lesson-angol-b1-egeszseg', 'szavak', 'arm', 'kar', 16, 'lcp-angol-b1-egeszseg'),
	('lc-enb1e-18', 'lesson-angol-b1-egeszseg', 'szavak', 'leg', 'láb', 17, 'lcp-angol-b1-egeszseg'),
	('lc-enb1e-19', 'lesson-angol-b1-egeszseg', 'szavak', 'hand', 'kéz', 18, 'lcp-angol-b1-egeszseg'),
	('lc-enb1e-20', 'lesson-angol-b1-egeszseg', 'szavak', 'appointment', 'időpont', 19, 'lcp-angol-b1-egeszseg');

INSERT OR IGNORE INTO lesson_cards (id, lesson_id, section_slug, front, back, sort, pack_id) VALUES
	('lc-enb1t-01', 'lesson-angol-b1-tech', 'szavak', 'computer', 'számítógép', 0, 'lcp-angol-b1-tech'),
	('lc-enb1t-02', 'lesson-angol-b1-tech', 'szavak', 'phone', 'telefon', 1, 'lcp-angol-b1-tech'),
	('lc-enb1t-03', 'lesson-angol-b1-tech', 'szavak', 'smartphone', 'okostelefon', 2, 'lcp-angol-b1-tech'),
	('lc-enb1t-04', 'lesson-angol-b1-tech', 'szavak', 'internet', 'internet', 3, 'lcp-angol-b1-tech'),
	('lc-enb1t-05', 'lesson-angol-b1-tech', 'szavak', 'website', 'weboldal', 4, 'lcp-angol-b1-tech'),
	('lc-enb1t-06', 'lesson-angol-b1-tech', 'szavak', 'password', 'jelszó', 5, 'lcp-angol-b1-tech'),
	('lc-enb1t-07', 'lesson-angol-b1-tech', 'szavak', 'screen', 'képernyő', 6, 'lcp-angol-b1-tech'),
	('lc-enb1t-08', 'lesson-angol-b1-tech', 'szavak', 'keyboard', 'billentyűzet', 7, 'lcp-angol-b1-tech'),
	('lc-enb1t-09', 'lesson-angol-b1-tech', 'szavak', 'mouse', 'számítógépes egér', 8, 'lcp-angol-b1-tech'),
	('lc-enb1t-10', 'lesson-angol-b1-tech', 'szavak', 'printer', 'nyomtató', 9, 'lcp-angol-b1-tech'),
	('lc-enb1t-11', 'lesson-angol-b1-tech', 'szavak', 'file', 'fájl', 10, 'lcp-angol-b1-tech'),
	('lc-enb1t-12', 'lesson-angol-b1-tech', 'szavak', 'folder', 'mappa', 11, 'lcp-angol-b1-tech'),
	('lc-enb1t-13', 'lesson-angol-b1-tech', 'szavak', 'message', 'üzenet', 12, 'lcp-angol-b1-tech'),
	('lc-enb1t-14', 'lesson-angol-b1-tech', 'szavak', 'send', 'küldeni', 13, 'lcp-angol-b1-tech'),
	('lc-enb1t-15', 'lesson-angol-b1-tech', 'szavak', 'download', 'letölteni', 14, 'lcp-angol-b1-tech'),
	('lc-enb1t-16', 'lesson-angol-b1-tech', 'szavak', 'upload', 'feltölteni', 15, 'lcp-angol-b1-tech'),
	('lc-enb1t-17', 'lesson-angol-b1-tech', 'szavak', 'battery', 'akkumulátor', 16, 'lcp-angol-b1-tech'),
	('lc-enb1t-18', 'lesson-angol-b1-tech', 'szavak', 'charger', 'töltő', 17, 'lcp-angol-b1-tech'),
	('lc-enb1t-19', 'lesson-angol-b1-tech', 'szavak', 'news', 'hírek', 18, 'lcp-angol-b1-tech'),
	('lc-enb1t-20', 'lesson-angol-b1-tech', 'szavak', 'social media', 'közösségi média', 19, 'lcp-angol-b1-tech'),
	('lc-enb1t-21', 'lesson-angol-b1-tech', 'szavak', 'account', 'fiók', 20, 'lcp-angol-b1-tech'),
	('lc-enb1t-22', 'lesson-angol-b1-tech', 'szavak', 'online', 'online, elérhető', 21, 'lcp-angol-b1-tech');

INSERT OR IGNORE INTO lesson_cards (id, lesson_id, section_slug, front, back, sort, pack_id) VALUES
	('lc-enb1v-01', 'lesson-angol-b1-velemeny', 'szavak', 'opinion', 'vélemény', 0, 'lcp-angol-b1-velemeny'),
	('lc-enb1v-02', 'lesson-angol-b1-velemeny', 'szavak', 'think', 'gondolni', 1, 'lcp-angol-b1-velemeny'),
	('lc-enb1v-03', 'lesson-angol-b1-velemeny', 'szavak', 'believe', 'hinni', 2, 'lcp-angol-b1-velemeny'),
	('lc-enb1v-04', 'lesson-angol-b1-velemeny', 'szavak', 'true', 'igaz', 3, 'lcp-angol-b1-velemeny'),
	('lc-enb1v-05', 'lesson-angol-b1-velemeny', 'szavak', 'false', 'hamis', 4, 'lcp-angol-b1-velemeny'),
	('lc-enb1v-06', 'lesson-angol-b1-velemeny', 'szavak', 'agree', 'egyetérteni', 5, 'lcp-angol-b1-velemeny'),
	('lc-enb1v-07', 'lesson-angol-b1-velemeny', 'szavak', 'disagree', 'nem érteni egyet', 6, 'lcp-angol-b1-velemeny'),
	('lc-enb1v-08', 'lesson-angol-b1-velemeny', 'szavak', 'happy', 'boldog', 7, 'lcp-angol-b1-velemeny'),
	('lc-enb1v-09', 'lesson-angol-b1-velemeny', 'szavak', 'sad', 'szomorú', 8, 'lcp-angol-b1-velemeny'),
	('lc-enb1v-10', 'lesson-angol-b1-velemeny', 'szavak', 'angry', 'mérges', 9, 'lcp-angol-b1-velemeny'),
	('lc-enb1v-11', 'lesson-angol-b1-velemeny', 'szavak', 'excited', 'izgatott', 10, 'lcp-angol-b1-velemeny'),
	('lc-enb1v-12', 'lesson-angol-b1-velemeny', 'szavak', 'bored', 'unatkozó', 11, 'lcp-angol-b1-velemeny'),
	('lc-enb1v-13', 'lesson-angol-b1-velemeny', 'szavak', 'proud', 'büszke', 12, 'lcp-angol-b1-velemeny'),
	('lc-enb1v-14', 'lesson-angol-b1-velemeny', 'szavak', 'worried', 'aggódó', 13, 'lcp-angol-b1-velemeny'),
	('lc-enb1v-15', 'lesson-angol-b1-velemeny', 'szavak', 'surprised', 'meglepett', 14, 'lcp-angol-b1-velemeny'),
	('lc-enb1v-16', 'lesson-angol-b1-velemeny', 'szavak', 'feeling', 'érzés', 15, 'lcp-angol-b1-velemeny'),
	('lc-enb1v-17', 'lesson-angol-b1-velemeny', 'szavak', 'love', 'szeretet, szeretni', 16, 'lcp-angol-b1-velemeny'),
	('lc-enb1v-18', 'lesson-angol-b1-velemeny', 'szavak', 'hate', 'gyűlölet, utálni', 17, 'lcp-angol-b1-velemeny'),
	('lc-enb1v-19', 'lesson-angol-b1-velemeny', 'szavak', 'important', 'fontos', 18, 'lcp-angol-b1-velemeny'),
	('lc-enb1v-20', 'lesson-angol-b1-velemeny', 'szavak', 'interesting', 'érdekes', 19, 'lcp-angol-b1-velemeny'),
	('lc-enb1v-21', 'lesson-angol-b1-velemeny', 'szavak', 'difficult', 'nehéz', 20, 'lcp-angol-b1-velemeny'),
	('lc-enb1v-22', 'lesson-angol-b1-velemeny', 'szavak', 'easy', 'könnyű', 21, 'lcp-angol-b1-velemeny');

-- 9) Német A1 kártyák ----------------------------------------------------------
INSERT OR IGNORE INTO lesson_cards (id, lesson_id, section_slug, front, back, sort, pack_id) VALUES
	('lc-dea1b-01', 'lesson-nemet-a1-begruesung', 'szavak', 'hallo', 'szia, hello', 0, 'lcp-nemet-a1-begruesung'),
	('lc-dea1b-02', 'lesson-nemet-a1-begruesung', 'szavak', 'guten Morgen', 'jó reggelt', 1, 'lcp-nemet-a1-begruesung'),
	('lc-dea1b-03', 'lesson-nemet-a1-begruesung', 'szavak', 'guten Tag', 'jó napot', 2, 'lcp-nemet-a1-begruesung'),
	('lc-dea1b-04', 'lesson-nemet-a1-begruesung', 'szavak', 'guten Abend', 'jó estét', 3, 'lcp-nemet-a1-begruesung'),
	('lc-dea1b-05', 'lesson-nemet-a1-begruesung', 'szavak', 'gute Nacht', 'jó éjszakát', 4, 'lcp-nemet-a1-begruesung'),
	('lc-dea1b-06', 'lesson-nemet-a1-begruesung', 'szavak', 'tschüss', 'szia búcsúzáskor', 5, 'lcp-nemet-a1-begruesung'),
	('lc-dea1b-07', 'lesson-nemet-a1-begruesung', 'szavak', 'auf Wiedersehen', 'viszontlátásra', 6, 'lcp-nemet-a1-begruesung'),
	('lc-dea1b-08', 'lesson-nemet-a1-begruesung', 'szavak', 'bitte', 'kérem, legyen szíves', 7, 'lcp-nemet-a1-begruesung'),
	('lc-dea1b-09', 'lesson-nemet-a1-begruesung', 'szavak', 'danke', 'köszönöm', 8, 'lcp-nemet-a1-begruesung'),
	('lc-dea1b-10', 'lesson-nemet-a1-begruesung', 'szavak', 'entschuldigung', 'elnézést, bocsánat', 9, 'lcp-nemet-a1-begruesung'),
	('lc-dea1b-11', 'lesson-nemet-a1-begruesung', 'szavak', 'ja', 'igen', 10, 'lcp-nemet-a1-begruesung'),
	('lc-dea1b-12', 'lesson-nemet-a1-begruesung', 'szavak', 'nein', 'nem', 11, 'lcp-nemet-a1-begruesung'),
	('lc-dea1b-13', 'lesson-nemet-a1-begruesung', 'szavak', 'ich heiße', 'a nevem', 12, 'lcp-nemet-a1-begruesung'),
	('lc-dea1b-14', 'lesson-nemet-a1-begruesung', 'szavak', 'wie heißt du', 'hogy hívnak', 13, 'lcp-nemet-a1-begruesung'),
	('lc-dea1b-15', 'lesson-nemet-a1-begruesung', 'szavak', 'freut mich', 'örülök a találkozásnak', 14, 'lcp-nemet-a1-begruesung'),
	('lc-dea1b-16', 'lesson-nemet-a1-begruesung', 'szavak', 'wie geht es dir', 'hogy vagy', 15, 'lcp-nemet-a1-begruesung'),
	('lc-dea1b-17', 'lesson-nemet-a1-begruesung', 'szavak', 'mir geht es gut', 'jól vagyok', 16, 'lcp-nemet-a1-begruesung'),
	('lc-dea1b-18', 'lesson-nemet-a1-begruesung', 'szavak', 'willkommen', 'üdvözöllek', 17, 'lcp-nemet-a1-begruesung'),
	('lc-dea1b-19', 'lesson-nemet-a1-begruesung', 'szavak', 'bis später', 'majd később', 18, 'lcp-nemet-a1-begruesung'),
	('lc-dea1b-20', 'lesson-nemet-a1-begruesung', 'szavak', 'der Name', 'név', 19, 'lcp-nemet-a1-begruesung');

INSERT OR IGNORE INTO lesson_cards (id, lesson_id, section_slug, front, back, sort, pack_id) VALUES
	('lc-dea1f-01', 'lesson-nemet-a1-familie', 'szavak', 'die Mutter', 'anya', 0, 'lcp-nemet-a1-familie'),
	('lc-dea1f-02', 'lesson-nemet-a1-familie', 'szavak', 'der Vater', 'apa', 1, 'lcp-nemet-a1-familie'),
	('lc-dea1f-03', 'lesson-nemet-a1-familie', 'szavak', 'die Eltern', 'szülők', 2, 'lcp-nemet-a1-familie'),
	('lc-dea1f-04', 'lesson-nemet-a1-familie', 'szavak', 'der Bruder', 'fiútestvér', 3, 'lcp-nemet-a1-familie'),
	('lc-dea1f-05', 'lesson-nemet-a1-familie', 'szavak', 'die Schwester', 'lánytestvér', 4, 'lcp-nemet-a1-familie'),
	('lc-dea1f-06', 'lesson-nemet-a1-familie', 'szavak', 'der Sohn', 'fiú gyermek', 5, 'lcp-nemet-a1-familie'),
	('lc-dea1f-07', 'lesson-nemet-a1-familie', 'szavak', 'die Tochter', 'lány gyermek', 6, 'lcp-nemet-a1-familie'),
	('lc-dea1f-08', 'lesson-nemet-a1-familie', 'szavak', 'das Kind', 'gyerek', 7, 'lcp-nemet-a1-familie'),
	('lc-dea1f-09', 'lesson-nemet-a1-familie', 'szavak', 'das Baby', 'baba', 8, 'lcp-nemet-a1-familie'),
	('lc-dea1f-10', 'lesson-nemet-a1-familie', 'szavak', 'der Ehemann', 'férj', 9, 'lcp-nemet-a1-familie'),
	('lc-dea1f-11', 'lesson-nemet-a1-familie', 'szavak', 'die Ehefrau', 'feleség', 10, 'lcp-nemet-a1-familie'),
	('lc-dea1f-12', 'lesson-nemet-a1-familie', 'szavak', 'die Familie', 'család', 11, 'lcp-nemet-a1-familie'),
	('lc-dea1f-13', 'lesson-nemet-a1-familie', 'szavak', 'die Großmutter', 'nagymama', 12, 'lcp-nemet-a1-familie'),
	('lc-dea1f-14', 'lesson-nemet-a1-familie', 'szavak', 'der Großvater', 'nagypapa', 13, 'lcp-nemet-a1-familie'),
	('lc-dea1f-15', 'lesson-nemet-a1-familie', 'szavak', 'der Onkel', 'nagybácsi', 14, 'lcp-nemet-a1-familie'),
	('lc-dea1f-16', 'lesson-nemet-a1-familie', 'szavak', 'die Tante', 'nagynéni', 15, 'lcp-nemet-a1-familie'),
	('lc-dea1f-17', 'lesson-nemet-a1-familie', 'szavak', 'der Cousin', 'unokatestvér fiú', 16, 'lcp-nemet-a1-familie'),
	('lc-dea1f-18', 'lesson-nemet-a1-familie', 'szavak', 'die Cousine', 'unokatestvér lány', 17, 'lcp-nemet-a1-familie'),
	('lc-dea1f-19', 'lesson-nemet-a1-familie', 'szavak', 'der Freund', 'barát', 18, 'lcp-nemet-a1-familie'),
	('lc-dea1f-20', 'lesson-nemet-a1-familie', 'szavak', 'der Junge', 'fiú', 19, 'lcp-nemet-a1-familie'),
	('lc-dea1f-21', 'lesson-nemet-a1-familie', 'szavak', 'das Mädchen', 'lány', 20, 'lcp-nemet-a1-familie'),
	('lc-dea1f-22', 'lesson-nemet-a1-familie', 'szavak', 'die Leute', 'emberek', 21, 'lcp-nemet-a1-familie');

INSERT OR IGNORE INTO lesson_cards (id, lesson_id, section_slug, front, back, sort, pack_id) VALUES
	('lc-dea1e-01', 'lesson-nemet-a1-essen', 'szavak', 'der Apfel', 'alma', 0, 'lcp-nemet-a1-essen'),
	('lc-dea1e-02', 'lesson-nemet-a1-essen', 'szavak', 'die Banane', 'banán', 1, 'lcp-nemet-a1-essen'),
	('lc-dea1e-03', 'lesson-nemet-a1-essen', 'szavak', 'die Orange', 'narancs', 2, 'lcp-nemet-a1-essen'),
	('lc-dea1e-04', 'lesson-nemet-a1-essen', 'szavak', 'das Brot', 'kenyér', 3, 'lcp-nemet-a1-essen'),
	('lc-dea1e-05', 'lesson-nemet-a1-essen', 'szavak', 'die Butter', 'vaj', 4, 'lcp-nemet-a1-essen'),
	('lc-dea1e-06', 'lesson-nemet-a1-essen', 'szavak', 'der Käse', 'sajt', 5, 'lcp-nemet-a1-essen'),
	('lc-dea1e-07', 'lesson-nemet-a1-essen', 'szavak', 'das Ei', 'tojás', 6, 'lcp-nemet-a1-essen'),
	('lc-dea1e-08', 'lesson-nemet-a1-essen', 'szavak', 'die Milch', 'tej', 7, 'lcp-nemet-a1-essen'),
	('lc-dea1e-09', 'lesson-nemet-a1-essen', 'szavak', 'der Kaffee', 'kávé', 8, 'lcp-nemet-a1-essen'),
	('lc-dea1e-10', 'lesson-nemet-a1-essen', 'szavak', 'der Tee', 'tea', 9, 'lcp-nemet-a1-essen'),
	('lc-dea1e-11', 'lesson-nemet-a1-essen', 'szavak', 'das Wasser', 'víz', 10, 'lcp-nemet-a1-essen'),
	('lc-dea1e-12', 'lesson-nemet-a1-essen', 'szavak', 'der Saft', 'gyümölcslé', 11, 'lcp-nemet-a1-essen'),
	('lc-dea1e-13', 'lesson-nemet-a1-essen', 'szavak', 'das Fleisch', 'hús', 12, 'lcp-nemet-a1-essen'),
	('lc-dea1e-14', 'lesson-nemet-a1-essen', 'szavak', 'der Fisch', 'hal', 13, 'lcp-nemet-a1-essen'),
	('lc-dea1e-15', 'lesson-nemet-a1-essen', 'szavak', 'das Hähnchen', 'csirke', 14, 'lcp-nemet-a1-essen'),
	('lc-dea1e-16', 'lesson-nemet-a1-essen', 'szavak', 'der Reis', 'rizs', 15, 'lcp-nemet-a1-essen'),
	('lc-dea1e-17', 'lesson-nemet-a1-essen', 'szavak', 'die Nudeln', 'tészta', 16, 'lcp-nemet-a1-essen'),
	('lc-dea1e-18', 'lesson-nemet-a1-essen', 'szavak', 'die Suppe', 'leves', 17, 'lcp-nemet-a1-essen'),
	('lc-dea1e-19', 'lesson-nemet-a1-essen', 'szavak', 'der Salat', 'saláta', 18, 'lcp-nemet-a1-essen'),
	('lc-dea1e-20', 'lesson-nemet-a1-essen', 'szavak', 'der Kuchen', 'sütemény', 19, 'lcp-nemet-a1-essen'),
	('lc-dea1e-21', 'lesson-nemet-a1-essen', 'szavak', 'der Zucker', 'cukor', 20, 'lcp-nemet-a1-essen'),
	('lc-dea1e-22', 'lesson-nemet-a1-essen', 'szavak', 'das Salz', 'só', 21, 'lcp-nemet-a1-essen');

INSERT OR IGNORE INTO lesson_cards (id, lesson_id, section_slug, front, back, sort, pack_id) VALUES
	('lc-dea1z-01', 'lesson-nemet-a1-zahlen', 'szavak', 'null', 'nulla', 0, 'lcp-nemet-a1-zahlen'),
	('lc-dea1z-02', 'lesson-nemet-a1-zahlen', 'szavak', 'eins', 'egy', 1, 'lcp-nemet-a1-zahlen'),
	('lc-dea1z-03', 'lesson-nemet-a1-zahlen', 'szavak', 'zwei', 'kettő', 2, 'lcp-nemet-a1-zahlen'),
	('lc-dea1z-04', 'lesson-nemet-a1-zahlen', 'szavak', 'drei', 'három', 3, 'lcp-nemet-a1-zahlen'),
	('lc-dea1z-05', 'lesson-nemet-a1-zahlen', 'szavak', 'vier', 'négy', 4, 'lcp-nemet-a1-zahlen'),
	('lc-dea1z-06', 'lesson-nemet-a1-zahlen', 'szavak', 'fünf', 'öt', 5, 'lcp-nemet-a1-zahlen'),
	('lc-dea1z-07', 'lesson-nemet-a1-zahlen', 'szavak', 'sechs', 'hat', 6, 'lcp-nemet-a1-zahlen'),
	('lc-dea1z-08', 'lesson-nemet-a1-zahlen', 'szavak', 'sieben', 'hét', 7, 'lcp-nemet-a1-zahlen'),
	('lc-dea1z-09', 'lesson-nemet-a1-zahlen', 'szavak', 'acht', 'nyolc', 8, 'lcp-nemet-a1-zahlen'),
	('lc-dea1z-10', 'lesson-nemet-a1-zahlen', 'szavak', 'neun', 'kilenc', 9, 'lcp-nemet-a1-zahlen'),
	('lc-dea1z-11', 'lesson-nemet-a1-zahlen', 'szavak', 'zehn', 'tíz', 10, 'lcp-nemet-a1-zahlen'),
	('lc-dea1z-12', 'lesson-nemet-a1-zahlen', 'szavak', 'elf', 'tizenegy', 11, 'lcp-nemet-a1-zahlen'),
	('lc-dea1z-13', 'lesson-nemet-a1-zahlen', 'szavak', 'zwölf', 'tizenkettő', 12, 'lcp-nemet-a1-zahlen'),
	('lc-dea1z-14', 'lesson-nemet-a1-zahlen', 'szavak', 'zwanzig', 'húsz', 13, 'lcp-nemet-a1-zahlen'),
	('lc-dea1z-15', 'lesson-nemet-a1-zahlen', 'szavak', 'hundert', 'száz', 14, 'lcp-nemet-a1-zahlen'),
	('lc-dea1z-16', 'lesson-nemet-a1-zahlen', 'szavak', 'tausend', 'ezer', 15, 'lcp-nemet-a1-zahlen'),
	('lc-dea1z-17', 'lesson-nemet-a1-zahlen', 'szavak', 'heute', 'ma', 16, 'lcp-nemet-a1-zahlen'),
	('lc-dea1z-18', 'lesson-nemet-a1-zahlen', 'szavak', 'morgen', 'holnap', 17, 'lcp-nemet-a1-zahlen'),
	('lc-dea1z-19', 'lesson-nemet-a1-zahlen', 'szavak', 'gestern', 'tegnap', 18, 'lcp-nemet-a1-zahlen'),
	('lc-dea1z-20', 'lesson-nemet-a1-zahlen', 'szavak', 'der Tag', 'nap', 19, 'lcp-nemet-a1-zahlen'),
	('lc-dea1z-21', 'lesson-nemet-a1-zahlen', 'szavak', 'die Woche', 'hét időszak', 20, 'lcp-nemet-a1-zahlen'),
	('lc-dea1z-22', 'lesson-nemet-a1-zahlen', 'szavak', 'der Monat', 'hónap', 21, 'lcp-nemet-a1-zahlen');

-- 10) Német A2 kártyák ---------------------------------------------------------
INSERT OR IGNORE INTO lesson_cards (id, lesson_id, section_slug, front, back, sort, pack_id) VALUES
	('lc-dea2w-01', 'lesson-nemet-a2-wohnen', 'szavak', 'das Haus', 'ház', 0, 'lcp-nemet-a2-wohnen'),
	('lc-dea2w-02', 'lesson-nemet-a2-wohnen', 'szavak', 'die Wohnung', 'lakás', 1, 'lcp-nemet-a2-wohnen'),
	('lc-dea2w-03', 'lesson-nemet-a2-wohnen', 'szavak', 'das Zimmer', 'szoba', 2, 'lcp-nemet-a2-wohnen'),
	('lc-dea2w-04', 'lesson-nemet-a2-wohnen', 'szavak', 'die Küche', 'konyha', 3, 'lcp-nemet-a2-wohnen'),
	('lc-dea2w-05', 'lesson-nemet-a2-wohnen', 'szavak', 'das Schlafzimmer', 'hálószoba', 4, 'lcp-nemet-a2-wohnen'),
	('lc-dea2w-06', 'lesson-nemet-a2-wohnen', 'szavak', 'das Bad', 'fürdőszoba', 5, 'lcp-nemet-a2-wohnen'),
	('lc-dea2w-07', 'lesson-nemet-a2-wohnen', 'szavak', 'das Wohnzimmer', 'nappali', 6, 'lcp-nemet-a2-wohnen'),
	('lc-dea2w-08', 'lesson-nemet-a2-wohnen', 'szavak', 'die Tür', 'ajtó', 7, 'lcp-nemet-a2-wohnen'),
	('lc-dea2w-09', 'lesson-nemet-a2-wohnen', 'szavak', 'das Fenster', 'ablak', 8, 'lcp-nemet-a2-wohnen'),
	('lc-dea2w-10', 'lesson-nemet-a2-wohnen', 'szavak', 'der Tisch', 'asztal', 9, 'lcp-nemet-a2-wohnen'),
	('lc-dea2w-11', 'lesson-nemet-a2-wohnen', 'szavak', 'der Stuhl', 'szék', 10, 'lcp-nemet-a2-wohnen'),
	('lc-dea2w-12', 'lesson-nemet-a2-wohnen', 'szavak', 'das Bett', 'ágy', 11, 'lcp-nemet-a2-wohnen'),
	('lc-dea2w-13', 'lesson-nemet-a2-wohnen', 'szavak', 'die Lampe', 'lámpa', 12, 'lcp-nemet-a2-wohnen'),
	('lc-dea2w-14', 'lesson-nemet-a2-wohnen', 'szavak', 'der Garten', 'kert', 13, 'lcp-nemet-a2-wohnen'),
	('lc-dea2w-15', 'lesson-nemet-a2-wohnen', 'szavak', 'die Wand', 'fal', 14, 'lcp-nemet-a2-wohnen'),
	('lc-dea2w-16', 'lesson-nemet-a2-wohnen', 'szavak', 'der Boden', 'padló', 15, 'lcp-nemet-a2-wohnen'),
	('lc-dea2w-17', 'lesson-nemet-a2-wohnen', 'szavak', 'der Schlüssel', 'kulcs', 16, 'lcp-nemet-a2-wohnen'),
	('lc-dea2w-18', 'lesson-nemet-a2-wohnen', 'szavak', 'die Miete', 'bérleti díj', 17, 'lcp-nemet-a2-wohnen'),
	('lc-dea2w-19', 'lesson-nemet-a2-wohnen', 'szavak', 'der Nachbar', 'szomszéd', 18, 'lcp-nemet-a2-wohnen'),
	('lc-dea2w-20', 'lesson-nemet-a2-wohnen', 'szavak', 'die Adresse', 'cím', 19, 'lcp-nemet-a2-wohnen');

INSERT OR IGNORE INTO lesson_cards (id, lesson_id, section_slug, front, back, sort, pack_id) VALUES
	('lc-dea2r-01', 'lesson-nemet-a2-reisen', 'szavak', 'reisen', 'utazni', 0, 'lcp-nemet-a2-reisen'),
	('lc-dea2r-02', 'lesson-nemet-a2-reisen', 'szavak', 'die Reise', 'utazás', 1, 'lcp-nemet-a2-reisen'),
	('lc-dea2r-03', 'lesson-nemet-a2-reisen', 'szavak', 'das Ticket', 'jegy', 2, 'lcp-nemet-a2-reisen'),
	('lc-dea2r-04', 'lesson-nemet-a2-reisen', 'szavak', 'der Zug', 'vonat', 3, 'lcp-nemet-a2-reisen'),
	('lc-dea2r-05', 'lesson-nemet-a2-reisen', 'szavak', 'der Bus', 'busz', 4, 'lcp-nemet-a2-reisen'),
	('lc-dea2r-06', 'lesson-nemet-a2-reisen', 'szavak', 'das Auto', 'autó', 5, 'lcp-nemet-a2-reisen'),
	('lc-dea2r-07', 'lesson-nemet-a2-reisen', 'szavak', 'das Flugzeug', 'repülőgép', 6, 'lcp-nemet-a2-reisen'),
	('lc-dea2r-08', 'lesson-nemet-a2-reisen', 'szavak', 'der Flughafen', 'repülőtér', 7, 'lcp-nemet-a2-reisen'),
	('lc-dea2r-09', 'lesson-nemet-a2-reisen', 'szavak', 'der Bahnhof', 'állomás', 8, 'lcp-nemet-a2-reisen'),
	('lc-dea2r-10', 'lesson-nemet-a2-reisen', 'szavak', 'die Karte', 'térkép', 9, 'lcp-nemet-a2-reisen'),
	('lc-dea2r-11', 'lesson-nemet-a2-reisen', 'szavak', 'links', 'balra', 10, 'lcp-nemet-a2-reisen'),
	('lc-dea2r-12', 'lesson-nemet-a2-reisen', 'szavak', 'rechts', 'jobbra', 11, 'lcp-nemet-a2-reisen'),
	('lc-dea2r-13', 'lesson-nemet-a2-reisen', 'szavak', 'geradeaus', 'egyenesen', 12, 'lcp-nemet-a2-reisen'),
	('lc-dea2r-14', 'lesson-nemet-a2-reisen', 'szavak', 'die Straße', 'utca', 13, 'lcp-nemet-a2-reisen'),
	('lc-dea2r-15', 'lesson-nemet-a2-reisen', 'szavak', 'die Stadt', 'város', 14, 'lcp-nemet-a2-reisen'),
	('lc-dea2r-16', 'lesson-nemet-a2-reisen', 'szavak', 'das Dorf', 'falu', 15, 'lcp-nemet-a2-reisen'),
	('lc-dea2r-17', 'lesson-nemet-a2-reisen', 'szavak', 'das Hotel', 'szálloda', 16, 'lcp-nemet-a2-reisen'),
	('lc-dea2r-18', 'lesson-nemet-a2-reisen', 'szavak', 'der Reisepass', 'útlevél', 17, 'lcp-nemet-a2-reisen'),
	('lc-dea2r-19', 'lesson-nemet-a2-reisen', 'szavak', 'der Koffer', 'bőrönd', 18, 'lcp-nemet-a2-reisen'),
	('lc-dea2r-20', 'lesson-nemet-a2-reisen', 'szavak', 'das Foto', 'fénykép', 19, 'lcp-nemet-a2-reisen'),
	('lc-dea2r-21', 'lesson-nemet-a2-reisen', 'szavak', 'der Urlaub', 'nyaralás, szabadság', 20, 'lcp-nemet-a2-reisen'),
	('lc-dea2r-22', 'lesson-nemet-a2-reisen', 'szavak', 'die Fahrt', 'utazás járművel', 21, 'lcp-nemet-a2-reisen');

INSERT OR IGNORE INTO lesson_cards (id, lesson_id, section_slug, front, back, sort, pack_id) VALUES
	('lc-dea2e-01', 'lesson-nemet-a2-einkaufen', 'szavak', 'kaufen', 'vásárolni', 0, 'lcp-nemet-a2-einkaufen'),
	('lc-dea2e-02', 'lesson-nemet-a2-einkaufen', 'szavak', 'der Laden', 'bolt', 1, 'lcp-nemet-a2-einkaufen'),
	('lc-dea2e-03', 'lesson-nemet-a2-einkaufen', 'szavak', 'der Markt', 'piac', 2, 'lcp-nemet-a2-einkaufen'),
	('lc-dea2e-04', 'lesson-nemet-a2-einkaufen', 'szavak', 'der Preis', 'ár', 3, 'lcp-nemet-a2-einkaufen'),
	('lc-dea2e-05', 'lesson-nemet-a2-einkaufen', 'szavak', 'billig', 'olcsó', 4, 'lcp-nemet-a2-einkaufen'),
	('lc-dea2e-06', 'lesson-nemet-a2-einkaufen', 'szavak', 'teuer', 'drága', 5, 'lcp-nemet-a2-einkaufen'),
	('lc-dea2e-07', 'lesson-nemet-a2-einkaufen', 'szavak', 'das Geld', 'pénz', 6, 'lcp-nemet-a2-einkaufen'),
	('lc-dea2e-08', 'lesson-nemet-a2-einkaufen', 'szavak', 'die Münze', 'érme', 7, 'lcp-nemet-a2-einkaufen'),
	('lc-dea2e-09', 'lesson-nemet-a2-einkaufen', 'szavak', 'die Bankkarte', 'bankkártya', 8, 'lcp-nemet-a2-einkaufen'),
	('lc-dea2e-10', 'lesson-nemet-a2-einkaufen', 'szavak', 'das Bargeld', 'készpénz', 9, 'lcp-nemet-a2-einkaufen'),
	('lc-dea2e-11', 'lesson-nemet-a2-einkaufen', 'szavak', 'das Wechselgeld', 'visszajáró', 10, 'lcp-nemet-a2-einkaufen'),
	('lc-dea2e-12', 'lesson-nemet-a2-einkaufen', 'szavak', 'die Quittung', 'nyugta, blokk', 11, 'lcp-nemet-a2-einkaufen'),
	('lc-dea2e-13', 'lesson-nemet-a2-einkaufen', 'szavak', 'die Tasche', 'táska', 12, 'lcp-nemet-a2-einkaufen'),
	('lc-dea2e-14', 'lesson-nemet-a2-einkaufen', 'szavak', 'die Größe', 'méret', 13, 'lcp-nemet-a2-einkaufen'),
	('lc-dea2e-15', 'lesson-nemet-a2-einkaufen', 'szavak', 'klein', 'kicsi', 14, 'lcp-nemet-a2-einkaufen'),
	('lc-dea2e-16', 'lesson-nemet-a2-einkaufen', 'szavak', 'groß', 'nagy', 15, 'lcp-nemet-a2-einkaufen'),
	('lc-dea2e-17', 'lesson-nemet-a2-einkaufen', 'szavak', 'der Rabatt', 'kedvezmény, akció', 16, 'lcp-nemet-a2-einkaufen'),
	('lc-dea2e-18', 'lesson-nemet-a2-einkaufen', 'szavak', 'offen', 'nyitva', 17, 'lcp-nemet-a2-einkaufen'),
	('lc-dea2e-19', 'lesson-nemet-a2-einkaufen', 'szavak', 'geschlossen', 'zárva', 18, 'lcp-nemet-a2-einkaufen'),
	('lc-dea2e-20', 'lesson-nemet-a2-einkaufen', 'szavak', 'zahlen', 'fizetni', 19, 'lcp-nemet-a2-einkaufen');

INSERT OR IGNORE INTO lesson_cards (id, lesson_id, section_slug, front, back, sort, pack_id) VALUES
	('lc-dea2v-01', 'lesson-nemet-a2-wetter', 'szavak', 'das Wetter', 'időjárás', 0, 'lcp-nemet-a2-wetter'),
	('lc-dea2v-02', 'lesson-nemet-a2-wetter', 'szavak', 'die Sonne', 'nap égitest', 1, 'lcp-nemet-a2-wetter'),
	('lc-dea2v-03', 'lesson-nemet-a2-wetter', 'szavak', 'der Regen', 'eső', 2, 'lcp-nemet-a2-wetter'),
	('lc-dea2v-04', 'lesson-nemet-a2-wetter', 'szavak', 'der Schnee', 'hó', 3, 'lcp-nemet-a2-wetter'),
	('lc-dea2v-05', 'lesson-nemet-a2-wetter', 'szavak', 'der Wind', 'szél', 4, 'lcp-nemet-a2-wetter'),
	('lc-dea2v-06', 'lesson-nemet-a2-wetter', 'szavak', 'die Wolke', 'felhő', 5, 'lcp-nemet-a2-wetter'),
	('lc-dea2v-07', 'lesson-nemet-a2-wetter', 'szavak', 'der Himmel', 'égbolt', 6, 'lcp-nemet-a2-wetter'),
	('lc-dea2v-08', 'lesson-nemet-a2-wetter', 'szavak', 'heiß', 'forró', 7, 'lcp-nemet-a2-wetter'),
	('lc-dea2v-09', 'lesson-nemet-a2-wetter', 'szavak', 'kalt', 'hideg', 8, 'lcp-nemet-a2-wetter'),
	('lc-dea2v-10', 'lesson-nemet-a2-wetter', 'szavak', 'warm', 'meleg', 9, 'lcp-nemet-a2-wetter'),
	('lc-dea2v-11', 'lesson-nemet-a2-wetter', 'szavak', 'kühl', 'hűvös', 10, 'lcp-nemet-a2-wetter'),
	('lc-dea2v-12', 'lesson-nemet-a2-wetter', 'szavak', 'der Sturm', 'vihar', 11, 'lcp-nemet-a2-wetter'),
	('lc-dea2v-13', 'lesson-nemet-a2-wetter', 'szavak', 'der Nebel', 'köd', 12, 'lcp-nemet-a2-wetter'),
	('lc-dea2v-14', 'lesson-nemet-a2-wetter', 'szavak', 'das Eis', 'jég', 13, 'lcp-nemet-a2-wetter'),
	('lc-dea2v-15', 'lesson-nemet-a2-wetter', 'szavak', 'die Jahreszeit', 'évszak', 14, 'lcp-nemet-a2-wetter'),
	('lc-dea2v-16', 'lesson-nemet-a2-wetter', 'szavak', 'der Frühling', 'tavasz', 15, 'lcp-nemet-a2-wetter'),
	('lc-dea2v-17', 'lesson-nemet-a2-wetter', 'szavak', 'der Sommer', 'nyár', 16, 'lcp-nemet-a2-wetter'),
	('lc-dea2v-18', 'lesson-nemet-a2-wetter', 'szavak', 'der Herbst', 'ősz', 17, 'lcp-nemet-a2-wetter'),
	('lc-dea2v-19', 'lesson-nemet-a2-wetter', 'szavak', 'der Winter', 'tél', 18, 'lcp-nemet-a2-wetter'),
	('lc-dea2v-20', 'lesson-nemet-a2-wetter', 'szavak', 'die Temperatur', 'hőmérséklet', 19, 'lcp-nemet-a2-wetter');

-- 11) Német B1 kártyák ---------------------------------------------------------
INSERT OR IGNORE INTO lesson_cards (id, lesson_id, section_slug, front, back, sort, pack_id) VALUES
	('lc-deb1a-01', 'lesson-nemet-b1-arbeit', 'szavak', 'die Arbeit', 'munka', 0, 'lcp-nemet-b1-arbeit'),
	('lc-deb1a-02', 'lesson-nemet-b1-arbeit', 'szavak', 'arbeiten', 'dolgozni', 1, 'lcp-nemet-b1-arbeit'),
	('lc-deb1a-03', 'lesson-nemet-b1-arbeit', 'szavak', 'das Büro', 'iroda', 2, 'lcp-nemet-b1-arbeit'),
	('lc-deb1a-04', 'lesson-nemet-b1-arbeit', 'szavak', 'der Kollege', 'kolléga', 3, 'lcp-nemet-b1-arbeit'),
	('lc-deb1a-05', 'lesson-nemet-b1-arbeit', 'szavak', 'der Chef', 'főnök', 4, 'lcp-nemet-b1-arbeit'),
	('lc-deb1a-06', 'lesson-nemet-b1-arbeit', 'szavak', 'die Besprechung', 'értekezlet', 5, 'lcp-nemet-b1-arbeit'),
	('lc-deb1a-07', 'lesson-nemet-b1-arbeit', 'szavak', 'die E-Mail', 'e-mail', 6, 'lcp-nemet-b1-arbeit'),
	('lc-deb1a-08', 'lesson-nemet-b1-arbeit', 'szavak', 'der Anruf', 'telefonhívás', 7, 'lcp-nemet-b1-arbeit'),
	('lc-deb1a-09', 'lesson-nemet-b1-arbeit', 'szavak', 'das Gehalt', 'fizetés', 8, 'lcp-nemet-b1-arbeit'),
	('lc-deb1a-10', 'lesson-nemet-b1-arbeit', 'szavak', 'die Bewerbung', 'jelentkezés', 9, 'lcp-nemet-b1-arbeit'),
	('lc-deb1a-11', 'lesson-nemet-b1-arbeit', 'szavak', 'das Vorstellungsgespräch', 'interjú', 10, 'lcp-nemet-b1-arbeit'),
	('lc-deb1a-12', 'lesson-nemet-b1-arbeit', 'szavak', 'die Schule', 'iskola', 11, 'lcp-nemet-b1-arbeit'),
	('lc-deb1a-13', 'lesson-nemet-b1-arbeit', 'szavak', 'der Lehrer', 'tanár', 12, 'lcp-nemet-b1-arbeit'),
	('lc-deb1a-14', 'lesson-nemet-b1-arbeit', 'szavak', 'der Schüler', 'diák', 13, 'lcp-nemet-b1-arbeit'),
	('lc-deb1a-15', 'lesson-nemet-b1-arbeit', 'szavak', 'die Hausaufgabe', 'házi feladat', 14, 'lcp-nemet-b1-arbeit'),
	('lc-deb1a-16', 'lesson-nemet-b1-arbeit', 'szavak', 'die Prüfung', 'vizsga', 15, 'lcp-nemet-b1-arbeit'),
	('lc-deb1a-17', 'lesson-nemet-b1-arbeit', 'szavak', 'die Universität', 'egyetem', 16, 'lcp-nemet-b1-arbeit'),
	('lc-deb1a-18', 'lesson-nemet-b1-arbeit', 'szavak', 'das Wissen', 'tudás', 17, 'lcp-nemet-b1-arbeit'),
	('lc-deb1a-19', 'lesson-nemet-b1-arbeit', 'szavak', 'die Fähigkeit', 'készség', 18, 'lcp-nemet-b1-arbeit'),
	('lc-deb1a-20', 'lesson-nemet-b1-arbeit', 'szavak', 'die Erfahrung', 'tapasztalat', 19, 'lcp-nemet-b1-arbeit'),
	('lc-deb1a-21', 'lesson-nemet-b1-arbeit', 'szavak', 'der Erfolg', 'siker', 20, 'lcp-nemet-b1-arbeit'),
	('lc-deb1a-22', 'lesson-nemet-b1-arbeit', 'szavak', 'die Stelle', 'állás, pozíció', 21, 'lcp-nemet-b1-arbeit');

INSERT OR IGNORE INTO lesson_cards (id, lesson_id, section_slug, front, back, sort, pack_id) VALUES
	('lc-deb1g-01', 'lesson-nemet-b1-gesundheit', 'szavak', 'die Gesundheit', 'egészség', 0, 'lcp-nemet-b1-gesundheit'),
	('lc-deb1g-02', 'lesson-nemet-b1-gesundheit', 'szavak', 'der Arzt', 'orvos', 1, 'lcp-nemet-b1-gesundheit'),
	('lc-deb1g-03', 'lesson-nemet-b1-gesundheit', 'szavak', 'das Krankenhaus', 'kórház', 2, 'lcp-nemet-b1-gesundheit'),
	('lc-deb1g-04', 'lesson-nemet-b1-gesundheit', 'szavak', 'das Medikament', 'gyógyszer', 3, 'lcp-nemet-b1-gesundheit'),
	('lc-deb1g-05', 'lesson-nemet-b1-gesundheit', 'szavak', 'der Schmerz', 'fájdalom', 4, 'lcp-nemet-b1-gesundheit'),
	('lc-deb1g-06', 'lesson-nemet-b1-gesundheit', 'szavak', 'die Kopfschmerzen', 'fejfájás', 5, 'lcp-nemet-b1-gesundheit'),
	('lc-deb1g-07', 'lesson-nemet-b1-gesundheit', 'szavak', 'das Fieber', 'láz', 6, 'lcp-nemet-b1-gesundheit'),
	('lc-deb1g-08', 'lesson-nemet-b1-gesundheit', 'szavak', 'der Husten', 'köhögés', 7, 'lcp-nemet-b1-gesundheit'),
	('lc-deb1g-09', 'lesson-nemet-b1-gesundheit', 'szavak', 'müde', 'fáradt', 8, 'lcp-nemet-b1-gesundheit'),
	('lc-deb1g-10', 'lesson-nemet-b1-gesundheit', 'szavak', 'die Ruhe', 'pihenés, nyugalom', 9, 'lcp-nemet-b1-gesundheit'),
	('lc-deb1g-11', 'lesson-nemet-b1-gesundheit', 'szavak', 'der Schlaf', 'alvás', 10, 'lcp-nemet-b1-gesundheit'),
	('lc-deb1g-12', 'lesson-nemet-b1-gesundheit', 'szavak', 'gesund', 'egészséges', 11, 'lcp-nemet-b1-gesundheit'),
	('lc-deb1g-13', 'lesson-nemet-b1-gesundheit', 'szavak', 'krank', 'beteg', 12, 'lcp-nemet-b1-gesundheit'),
	('lc-deb1g-14', 'lesson-nemet-b1-gesundheit', 'szavak', 'der Körper', 'test', 13, 'lcp-nemet-b1-gesundheit'),
	('lc-deb1g-15', 'lesson-nemet-b1-gesundheit', 'szavak', 'das Herz', 'szív', 14, 'lcp-nemet-b1-gesundheit'),
	('lc-deb1g-16', 'lesson-nemet-b1-gesundheit', 'szavak', 'das Blut', 'vér', 15, 'lcp-nemet-b1-gesundheit'),
	('lc-deb1g-17', 'lesson-nemet-b1-gesundheit', 'szavak', 'der Arm', 'kar', 16, 'lcp-nemet-b1-gesundheit'),
	('lc-deb1g-18', 'lesson-nemet-b1-gesundheit', 'szavak', 'das Bein', 'láb', 17, 'lcp-nemet-b1-gesundheit'),
	('lc-deb1g-19', 'lesson-nemet-b1-gesundheit', 'szavak', 'die Hand', 'kéz', 18, 'lcp-nemet-b1-gesundheit'),
	('lc-deb1g-20', 'lesson-nemet-b1-gesundheit', 'szavak', 'der Termin', 'időpont', 19, 'lcp-nemet-b1-gesundheit');

INSERT OR IGNORE INTO lesson_cards (id, lesson_id, section_slug, front, back, sort, pack_id) VALUES
	('lc-deb1t-01', 'lesson-nemet-b1-tech', 'szavak', 'der Computer', 'számítógép', 0, 'lcp-nemet-b1-tech'),
	('lc-deb1t-02', 'lesson-nemet-b1-tech', 'szavak', 'das Handy', 'mobiltelefon', 1, 'lcp-nemet-b1-tech'),
	('lc-deb1t-03', 'lesson-nemet-b1-tech', 'szavak', 'das Internet', 'internet', 2, 'lcp-nemet-b1-tech'),
	('lc-deb1t-04', 'lesson-nemet-b1-tech', 'szavak', 'die Webseite', 'weboldal', 3, 'lcp-nemet-b1-tech'),
	('lc-deb1t-05', 'lesson-nemet-b1-tech', 'szavak', 'das Passwort', 'jelszó', 4, 'lcp-nemet-b1-tech'),
	('lc-deb1t-06', 'lesson-nemet-b1-tech', 'szavak', 'der Bildschirm', 'képernyő', 5, 'lcp-nemet-b1-tech'),
	('lc-deb1t-07', 'lesson-nemet-b1-tech', 'szavak', 'die Tastatur', 'billentyűzet', 6, 'lcp-nemet-b1-tech'),
	('lc-deb1t-08', 'lesson-nemet-b1-tech', 'szavak', 'die Maus', 'számítógépes egér', 7, 'lcp-nemet-b1-tech'),
	('lc-deb1t-09', 'lesson-nemet-b1-tech', 'szavak', 'der Drucker', 'nyomtató', 8, 'lcp-nemet-b1-tech'),
	('lc-deb1t-10', 'lesson-nemet-b1-tech', 'szavak', 'die Datei', 'fájl', 9, 'lcp-nemet-b1-tech'),
	('lc-deb1t-11', 'lesson-nemet-b1-tech', 'szavak', 'der Ordner', 'mappa', 10, 'lcp-nemet-b1-tech'),
	('lc-deb1t-12', 'lesson-nemet-b1-tech', 'szavak', 'die Nachricht', 'üzenet, hír', 11, 'lcp-nemet-b1-tech'),
	('lc-deb1t-13', 'lesson-nemet-b1-tech', 'szavak', 'senden', 'küldeni', 12, 'lcp-nemet-b1-tech'),
	('lc-deb1t-14', 'lesson-nemet-b1-tech', 'szavak', 'herunterladen', 'letölteni', 13, 'lcp-nemet-b1-tech'),
	('lc-deb1t-15', 'lesson-nemet-b1-tech', 'szavak', 'hochladen', 'feltölteni', 14, 'lcp-nemet-b1-tech'),
	('lc-deb1t-16', 'lesson-nemet-b1-tech', 'szavak', 'der Akku', 'akkumulátor', 15, 'lcp-nemet-b1-tech'),
	('lc-deb1t-17', 'lesson-nemet-b1-tech', 'szavak', 'das Ladegerät', 'töltő', 16, 'lcp-nemet-b1-tech'),
	('lc-deb1t-18', 'lesson-nemet-b1-tech', 'szavak', 'die Nachrichten', 'hírek', 17, 'lcp-nemet-b1-tech'),
	('lc-deb1t-19', 'lesson-nemet-b1-tech', 'szavak', 'die sozialen Medien', 'közösségi média', 18, 'lcp-nemet-b1-tech'),
	('lc-deb1t-20', 'lesson-nemet-b1-tech', 'szavak', 'das Konto', 'fiók', 19, 'lcp-nemet-b1-tech'),
	('lc-deb1t-21', 'lesson-nemet-b1-tech', 'szavak', 'online', 'online', 20, 'lcp-nemet-b1-tech'),
	('lc-deb1t-22', 'lesson-nemet-b1-tech', 'szavak', 'der Anhang', 'melléklet', 21, 'lcp-nemet-b1-tech');

INSERT OR IGNORE INTO lesson_cards (id, lesson_id, section_slug, front, back, sort, pack_id) VALUES
	('lc-deb1v-01', 'lesson-nemet-b1-meinung', 'szavak', 'die Meinung', 'vélemény', 0, 'lcp-nemet-b1-meinung'),
	('lc-deb1v-02', 'lesson-nemet-b1-meinung', 'szavak', 'denken', 'gondolni', 1, 'lcp-nemet-b1-meinung'),
	('lc-deb1v-03', 'lesson-nemet-b1-meinung', 'szavak', 'glauben', 'hinni', 2, 'lcp-nemet-b1-meinung'),
	('lc-deb1v-04', 'lesson-nemet-b1-meinung', 'szavak', 'wahr', 'igaz', 3, 'lcp-nemet-b1-meinung'),
	('lc-deb1v-05', 'lesson-nemet-b1-meinung', 'szavak', 'falsch', 'hamis, rossz', 4, 'lcp-nemet-b1-meinung'),
	('lc-deb1v-06', 'lesson-nemet-b1-meinung', 'szavak', 'einverstanden', 'egyetértő', 5, 'lcp-nemet-b1-meinung'),
	('lc-deb1v-07', 'lesson-nemet-b1-meinung', 'szavak', 'nicht einverstanden', 'nem ért egyet', 6, 'lcp-nemet-b1-meinung'),
	('lc-deb1v-08', 'lesson-nemet-b1-meinung', 'szavak', 'glücklich', 'boldog', 7, 'lcp-nemet-b1-meinung'),
	('lc-deb1v-09', 'lesson-nemet-b1-meinung', 'szavak', 'traurig', 'szomorú', 8, 'lcp-nemet-b1-meinung'),
	('lc-deb1v-10', 'lesson-nemet-b1-meinung', 'szavak', 'wütend', 'mérges', 9, 'lcp-nemet-b1-meinung'),
	('lc-deb1v-11', 'lesson-nemet-b1-meinung', 'szavak', 'aufgeregt', 'izgatott', 10, 'lcp-nemet-b1-meinung'),
	('lc-deb1v-12', 'lesson-nemet-b1-meinung', 'szavak', 'gelangweilt', 'unatkozó', 11, 'lcp-nemet-b1-meinung'),
	('lc-deb1v-13', 'lesson-nemet-b1-meinung', 'szavak', 'stolz', 'büszke', 12, 'lcp-nemet-b1-meinung'),
	('lc-deb1v-14', 'lesson-nemet-b1-meinung', 'szavak', 'besorgt', 'aggódó', 13, 'lcp-nemet-b1-meinung'),
	('lc-deb1v-15', 'lesson-nemet-b1-meinung', 'szavak', 'überrascht', 'meglepett', 14, 'lcp-nemet-b1-meinung'),
	('lc-deb1v-16', 'lesson-nemet-b1-meinung', 'szavak', 'das Gefühl', 'érzés', 15, 'lcp-nemet-b1-meinung'),
	('lc-deb1v-17', 'lesson-nemet-b1-meinung', 'szavak', 'die Liebe', 'szeretet', 16, 'lcp-nemet-b1-meinung'),
	('lc-deb1v-18', 'lesson-nemet-b1-meinung', 'szavak', 'der Hass', 'gyűlölet', 17, 'lcp-nemet-b1-meinung'),
	('lc-deb1v-19', 'lesson-nemet-b1-meinung', 'szavak', 'wichtig', 'fontos', 18, 'lcp-nemet-b1-meinung'),
	('lc-deb1v-20', 'lesson-nemet-b1-meinung', 'szavak', 'interessant', 'érdekes', 19, 'lcp-nemet-b1-meinung'),
	('lc-deb1v-21', 'lesson-nemet-b1-meinung', 'szavak', 'schwierig', 'nehéz', 20, 'lcp-nemet-b1-meinung'),
	('lc-deb1v-22', 'lesson-nemet-b1-meinung', 'szavak', 'leicht', 'könnyű', 21, 'lcp-nemet-b1-meinung');
